### PR TITLE
[#359] Rename `realm_secret` to `access_token_secret`

### PR DESCRIPTION
**Pull request by MartinFlores751**

### CODE REVIEW

**Comment by MartinFlores751** [comment]
All tests passed.

```console
$ pytest
...
============================= test session starts ==============================
...

test_auth_endpoint.py ...............s...                                [ 15%]
test_irods_http_api.py s.......s...........................s...........s [ 57%]
...................s...ss...ss..sss..sss...s.s.....                      [100%]

======================= 101 passed, 18 skipped in 19.45s =======================
```

**Comment by korydraughn** [comment]
Please confirm the OIDC code works as well since it's been changed. One test to confirm the code path which originally used `realm_secret` works with the new name.

**Review by alanking — APPROVED** [review]

**Comment by alanking** [comment]
Let's go ahead and rebase the changes - there are conflicts to resolve.

**Comment by MartinFlores751** [comment]
Rebase.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Review by alanking — APPROVED** [review]
\# it

**Comment by MartinFlores751** [comment]
Pounded.

**Pull request merged**
