### PR TITLE
[#120] Run clang-format on all hpp/cpp files

### PR DESCRIPTION
**Pull request by korydraughn**
The formatting of the nlohmann json objects isn't the best, it's not a blocker.

We can take care of those in a later PR.

### CODE REVIEW

**Comment by korydraughn** [comment]
All tests passed.

I cannot test OIDC code path and that's okay since this PR is all about formatting.

**Comment by alanking** [comment]
There are two open PRs in this repo that would be impacted by merging this. Should we yield to those, or have them fall in line with the new formatting?

**Comment by korydraughn** [comment]
Let's get the OIDC PR in first.

**Comment by trel** [comment]
gettin' that minus.

**Comment by korydraughn** [comment]
Well, more like clang-format touching every file.

**Comment by korydraughn** [comment]
Pounding.

**Comment by trel** [comment]
-32, don't knock it.

**Comment by trel** [comment]
it's so greeeeeen.

**Comment by korydraughn** [comment]
Finally formatted the source!

**Pull request merged**
