### PR TITLE
More 0.1.0 changes

### PR DESCRIPTION
**Pull request by korydraughn**
All tests pass.

Changing the response structure required formatting lots of code. Consider looking at each commit in isolation. The last commit is just formatting + one code comment adjustment.

Client IP addresses aren't logged yet, but this PR makes it possible to capture them. I haven't decided how to handle that. Still thinking through the design and implementation. Logging IPs is looking like a 0.2.0 thing.

### CODE REVIEW

**Comment by korydraughn** [comment]
Turns out you can hold shift and select the commits you'd like to view.

**Comment by trel** [comment]
i see IP was made available... did you use it in the logging yet?

**Comment by trel** [comment]
oh, reading your comment in the OP helps.   english is good.

**Review by trel — APPROVED** [review]
get some issue IDs in the commit messages and it seems good to go from here.

**Comment by korydraughn** [comment]
Passed tests. Pounding.

**Comment by korydraughn** [comment]
Done.

**Pull request merged**
