### PR TITLE
Access token handling

### PR DESCRIPTION
**Pull request by bl000m**
The Access Token Validation feature introduces an endpoint for validating access tokens, ensuring its integrity and authenticity  before granting access to protected resources.

I experimented with your Api in a test instance to allow a portal (still a work in progress) to access iRODS through the API using an access token issued by the same OIDC provider configured in the iRODS HTTP API (SSO), as discussed [here](https://github.com/irods/irods_client_http_api/issues/227). 

I implemented this feature to test OIDC compatibility, and everything worked seamlessly on my end.

I thought it would be interesting for you to test on your side and potentially integrate it if you believe it could benefit other users as well. 
Below some details:

**Endpoint**
The` /validate-token` endpoint is responsible for validating the provided access token and generating a new bearer token.

_Request_
`curl -X POST -H 'Authorization: Bearer <access_token>' http://localhost:<port>/irods-http-api/<version>/validate-token`

_Response_
If the access token is valid, the response will contain a new bearer token, which can be used for subsequent operations.
```
{
    "success": true,
    "bearer_token": "<new_bearer_token>"
}
```
This endpoint follows the OAuth 2.0 protocol for token validation and issuance.

**Implementation Details**

**Testing**: Conducted thorough testing on a test instance running on VM with Ubuntu 22.04, including setup script for launching Docker container and updating dependencies  => `launch_docker.sh`
**Dependency Management**: Updated the CMake architecture of dependencies to ensure compatibility.
**Integration**: Integrated the endpoint to create, if the access token is validated, the bearer token that matches the `struct `currently used in the `resolve_client_identity` function to cast the info extracted from the token (struct `authenticated_client_info`).
**Portal Integration**: Implemented functionality to allow the portal to access iRODS by 
- making a POST Request to the iRODS HTTP API `/authenticate` endpoint to obtain the` authorization code`
- using this code to obtain the `AT` from the OIDC provider 
- finally making a POST Request to the newly implemented iRODS HTTP API `/validate-token` endpoint to obtain the iRODS Bearer Token to be used for further fetching

**Scope Enhancement:** Added the `"profile"` scope in the implementation of the code for the `/authenticate` handler in the iRODS HTTP API (in the args of the request url building) to ensure the correct authorization code is obtained from the OIDC provider, allowing access to the `"preferred_username`" claim in the access token.

**Documentation Updates**
- Updated the README and API documentation to reflect the new feature
- Added comments within the codebase for clarity.

**Note**
This feature aims to ensure compatibility with OIDC providers and enable seamless integration with portals and other external systems. However, further testing with different OIDC providers may be required to confirm compatibility.

### CODE REVIEW

**Comment by korydraughn** [comment]
Thank you for this.

We'll review and let you know our thoughts.

**Comment by MartinFlores751** [comment]
Hello @bl000m, we were hoping to get your opinion on PR #252. The work done is similar to what you have done, and we would like to know if it would solve your particular problem too.

**Comment by bl000m** [comment]
hello @MartinFlores751 

Wth pleasure:

- The program is not compiling because "run_as_protected_resources" is set as type string in the JSON schema in main.cpp. It needs to be boolean since you retrieve its value here as boolean; otherwise, the program will not compile:
```
if (oidc_stanza_exists) {
    static const auto is_client{irods::http::globals::oidc_configuration().at("run_as_protected_resource").get<bool>()};
    return is_client;
}
```
So:
```
// main.cpp
"run_as_protected_resource": {{
                                    - "type": "string"
                                    + "type": "boolean"
                                }},
```
and

```
- "run_as_protected_resource": "<string>",
+ "run_as_protected_resource": "<boolean>",
```
Also, when you: 
```
const auto& mappings{irods::http::globals::oidc_configuration().at("user_attribute_mapping")};, 
```
you are referring to something that is not required in the JSON schema and that throws an error. So either you change the JSON schema in main.cpp, adding the `user_attribute_mapping`, or you remove the section and refer just to the `irods_user_claim` value as mapping with the OIDC provider user, that in my opinion is the best solution. 

Changing the `run_as_protected_resources`type to boolean and removing the  `user_attribute_mapping`retrieving code snippet and replacing it with the `irods_user_claim`value as mapping value  I was able to make it work by first making a GET request to retrieve the authorization code, adding the 'profile' scope, and asking for the access token. Then, making a POST request to other endpoints, in particular, the collection list.

My thoughts:

In your code, you've opted to enable fetching endpoints with an OIDC access token. However, this requires altering the logic in `resolve_client_identity` within `common.cpp`. Additionally, the iteration on `user_attribute_mapping`, even if it were correctly required, doesn't seem to be the optimal solution.

The `/authenticate` handler has grown to over 300 lines, with an abundance of conditional statements that hinder readability. While the choice of architecture is ultimately yours, I'd suggest considering alternatives to avoid overloading the `/authenticate` handler. Moreover, refraining from making significant changes to the logic in `resolve_client_identity` and minimizing the number of configuration parameters in `config.json` can prevent confusion.

A potential solution could be to create a new endpoint, as I proposed in my PR, dedicated to hitting, as you better did, the introspection OIDC provider endpoint for validation. This approach would entail sending back the iRODS token as a response to the validation request, that at the end of the day appears to be the best solution to grant access to fetch all endpoints. This alternative could offer a lighter solution, enhancing readability and promoting separation of concerns.

**Comment by trel** [comment]
Additional scopes is https://github.com/irods/irods_client_http_api/issues/248

**Comment by MartinFlores751** [comment]
Thank you for the comments, certainly brought up some good points.

> The program is not compiling because run_as_protected_resources is set as type string in the JSON schema in core/src/main.cpp.

> the user_attribute_mapping you are referring to is not required in the JSON schema and that throws an error.

Yes, these are mistakes that I will be fixing.

> ...just to the irods_user_claim value as mapping with the OIDC provider user, that in my opinion is the best solution, since the user_attribute_mapping logic seems a bit unintuitive, and I'm not sure it could work in all cases, for sure not in my case.

The idea is that the `user_attribute_mapping` is a more advanced version of `irods_user_claim`. The `irods_user_claim` wants the username directly, whereas the `user_attribute_mapping` is looking for several properties to match against. The reasoning behind this is that we assume not everyone has access to modify their OpenID Provider. As such, an alternate user mapping method is required. You are right that we should consider allowing `irods_user_claim` to work there too.

> The /authenticate handler signature function has grown to over 300 lines, with an abundance of conditional statements that hinder readability. While the architecture choice is ultimately yours, and I understand the strategy of consolidating various scenarios into a few main endpoint handlers to prevent dispersion, I recommend exploring alternatives to prevent overloading the /authenticate handler.

I understand the concerns about the `/authenticate` endpoint. We are planning to refactor the code to make it easier to follow.

> Moreover, refraining from making significant changes to the logic in resolve_client_identity and minimizing the number of configuration parameters in config.json can prevent confusion.

The new code in `resolve_client_identity` will be refactored. This should improve readability. On the configuration parameters, you are right. Reducing configuration parameters, if possible, would be beneficial.

> Creating a new endpoint for handling access token validation in order to release the iRODS token needed for accessing all endpoints could be beneficial, moving the hit_intro_endpoint logic into it. This approach would entail sending back the iRODS token as a response to the validation request, that at the end of the day appears to be the best solution to grant access to fetch all endpoints without revolutioning the existing code. This alternative could offer a lighter solution, enhancing readability and promoting separation of concerns.

I agree, using the iRODS token would be the lighter solution, however, the goal of #252 is to provide improved and easier integration with OpenID clients. By using the iRODS token, integration would be more difficult, as clients now need to handle an additional token instead of using what they already have. There are also additional benefits we receive by using access tokens instead of iRODS tokens, such as expiration and revocation handled by the OpenID Provider.

> ...it is necessary to include the profile scope in the arguments of the redirect URL to the authorization endpoint. ...

Yes, this will be resolved in #248.

**Pull request closed without merging**
