### PR TITLE
[#239] Add schema and template for 'state_timeout_in_seconds'

### PR DESCRIPTION
**Pull request by MartinFlores751**

### CODE REVIEW

**Comment by trel** [comment]
and this was already in the readme?

**Comment by MartinFlores751** [comment]
Yep, you can find it in main: https://github.com/irods/irods_client_http_api/blob/cfb0c76e37bac83fa4a5f344e089e06ab251752b/README.md?plain=1#L269-L271

Blame says it was in 0.1.0.

**Comment by MartinFlores751** [comment]
Think this is the specific commit it was added in the readme: https://github.com/irods/irods_client_http_api/commit/f54fc3c56ff9f250519b30a3e650c65273b5bcfe

**Comment by trel** [comment]
perfect.

**Review by korydraughn — COMMENTED** [review]
Changes look good. Those sections of the code need to use spaces. Looks like the PR is following that rule, but can't confirm that using my phone. Is everything here using spaces for alignment?

**Review by korydraughn — APPROVED** [review]
This PR is good.

Please pound it.

**Comment by MartinFlores751** [comment]
Pounded.

**Pull request merged**
