### PR TITLE
[irods/irods#6251,irods/irods#6256] find_package for fmt and spdlog

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#6251
In service of irods/irods#6256

Once this is merged, a 4-3-stable branch should be created.

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Pound it.

**Review by alanking — APPROVED** [review]

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by alanking** [comment]
Created 4-3-stable branch based on https://github.com/irods/irods_client_http_api/commit/78ef3880d27ad4dc038897c8a0bd6a9416d8f5a6.

We may need to create a branch for development against 4.3.1's build system (thinking about the open PRs and possible other development work going on). Thoughts?

**Comment by korydraughn** [comment]
@alanking I'm assuming that's because the externals are changing?

@SwooshyCueb Do these changes depend on new externals packages? Are those new externals packages incompatible with 4.3.1?

**Comment by SwooshyCueb** [comment]
> Do these changes depend on new externals packages?

Not these. The changes in #256 and #257 do though.

> Are those new externals packages incompatible with 4.3.1?

Yes. All externals explicitly built against libc++ have moved into different subfolders, clang and clang-runtime have updated, and spdlog now has a shared library.

**Comment by alanking** [comment]
Right, just depends on whether we are okay with releasing while building against *unreleased* dev and/or runtime packages (if I'm understanding everything correctly). This is pre-1.0, so... maybe okay?

**Comment by alanking** [comment]
Y'know what, it doesn't really matter. I think I got confused and assumed the fmt find module was something we made. Carry on.

**Comment by korydraughn** [comment]
I just confirmed tip of main for this repo no longer compiles with 4.3.1 packages and that's fine.

We can create a new branch for 4.3.1 development when that time comes. The SHA to branch from is 0720f71e66383db52782f3aca1565f9bcfd269d2 _(according to @SwooshyCueb)_.

**Comment by korydraughn** [comment]
Thinking about it more, let's go ahead and create a branch for 4.3.1 development.

@MartinFlores751's OIDC work will need to be available for 4.3.1 once it's complete.

**Pull request merged**
